version: '3.4'

services:
  gamemaster.app:
    container_name: web_gm
    env_file:
      - ~/.gamemaster.env.${ASPNETCORE_ENVIRONMENT}
    build:
      context: .
    restart:
      always
    volumes:
      - /root/.nuget:/root/.nuget
    logging:
      options:
        max-size: "5m"
        max-file: "10"

  gamemaster.proxy:
    env_file:
      - ~/.gamemaster.env.${ASPNETCORE_ENVIRONMENT}
    volumes:
      - /root/data/caddy_data/:/data
      - /root/data/caddy_config/:/config
    container_name: proxy_gm
    restart:
      always
    build:
      context: ${gamemaster_proxy:-./proxy}
    ports:
      - 443:443
      - 80:80
    logging:
      options:
        max-size: "5m"
        max-file: "10"

  gamemaster.db:
    env_file:
      - ~/.gamemaster.env.${ASPNETCORE_ENVIRONMENT}
    image: mongo:latest
    container_name: db_gm
    restart:
      always
    volumes:
      -  /root/data/db:/data/db
    logging:
      options:
        max-size: "5m"
        max-file: "10"